apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: custom-gitlab
data:
  GITLAB_EXTERNAL_URL: "http://dev-gitlab.cognet9.com"

  GITLAB_OMNIBUS_CONFIG: |
    external_url ENV['GITLAB_EXTERNAL_URL']
    # 컨테이너 내부는 80 listen으로 고정 (외부 노출 포트는 hostPort에서 매핑)
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    gitlab_rails['initial_root_password'] = ENV['GITLAB_ROOT_PASSWORD']
    # 테스트용 최소 리소스
    puma['worker_processes'] = 2
    sidekiq['max_concurrency'] = 10
    prometheus_monitoring['enable'] = false
    gitlab_rails['gitlab_default_can_create_group'] = true
    gitlab_rails['gitlab_username_changing_enabled'] = true
    gitlab_rails['gitlab_signup_enabled'] = false
